export const bots = [
    {
        id: "dcf17418",
        name: "CREO Demo",
        type: "Widget",
        imageUrl: "https://s3.us-west-2.amazonaws.com/cdn.devlabs.tech/botImage/kg8el74o-ndabeqoa.png",
        companyId: 135,
        inProduction: 0,
        properties: {
            cacheLimits: [
                {
                    id: "a80adee3-32ed-472a-9050-81a246280b75",
                    name: "cedula",
                    type: "text",
                    label: "cedula",
                    rules: {
                        rules: "numeric",
                        isObligatory: false,
                    },
                },
            ],
            mergeBubbles: false,
            operatorView: {
                byTeam: false,
                workingDays: ["1"],
                isEnableWorkingDays: true,
                workingDaysDetailed: {
                    1: {
                        finalHour: "00:00",
                        initialHour: "00:00",
                    },
                },
            },
            cancelExpressions: "salir, exit",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "593988649360",
        name: "Dev Acc",
        type: "Whatsapp",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {
            session: {
                WAToken1: '"vs2MvpYODjfB5hIO5tHEMaMeiwEi+8bzh1aX7q4oFbc="',
                WAToken2: '"1@EOCDN/GIBMUymtF/hKLe0BH7U3BstEtvrq+MiVZwFL/yGjQP5p0pSOu7wZRZAY1VtewIr0QGiPIcwQ=="',
                WABrowserId: '"qVCI6RbIspr5p2woZEf+KQ=="',
                WASecretBundle:
                    '{"key":"3fpoldyZJWk9LjDLC2J51L5OJdG/bUajfiUg1Lq9vU8=","encKey":"txKf1K7eb6JbYXMVeiqE6kbknvP00WqiapDr7qwoQQg=","macKey":"3fpoldyZJWk9LjDLC2J51L5OJdG/bUajfiUg1Lq9vU8="}',
            },
            provider: {
                name: "venom",
                driver: "Venom",
            },
            operatorView: {
                states: ["end", "wait"],
                canSwitch: true,
                timesLimit: {
                    wait: 60,
                },
                workingDays: ["1", "2", "3", "4", "5"],
                workingHours: {
                    finalHour: "18:00",
                    initialHour: "09:00",
                },
                uniqueSession: false,
                canRecoverChat: true,
                messagesToUser: {
                    end: "Esta sesión ha expirado",
                    wait: "Este es un mensaje de alerta que se expirara pronto - usuario",
                    operatorCloseSession: "Esta sesión ha terminado, ha sido un placer atenderte.",
                },
                limitTimeOperator: 60,
                isEnableWorkingDays: true,
            },
            redirectWebhookUrl: "",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "108536757948849_Feed",
        name: "Facebook Feed",
        type: "Facebook_Feed",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {
            scrubbingRule: 1,
            messengerBotId: "108536757948849",
            redirectWebhookUrl: "",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "108536757948849",
        name: "fb test1",
        type: "Facebook",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {
            trial: true,
            operator: true,
            provider: {
                app: {
                    keyId: "app_5e75370e132b14000f820617",
                    secret: "I9V8miJWbK0A8VhIevI7Czz45RVSIOJOpxpo6liGjTpvy4d196bxyEWVfS14Zf6XbQ4zsvDn3Q-Ced5It6LslQ",
                },
                name: "facebook",
                account: {
                    keyId: "act_5d4889a7db751a001073bd74",
                    secret: "MfWzl40zzx31eiaeJ1ENZIpigD5bEW99IxPXo1RBOpO7ZWJFsZH4MwhoP7XxM_3K9pQeUm1XvNYXLpuS8xCj3A",
                },
                namespace: "e0f2cbcc_1ca9_4a8a_b38a_914e0c9cc679",
                credentials: {
                    appId: "5e4dca27aa83eb000f6c4f7e",
                },
            },
            smoochId: "5e4dca27aa83eb000f6c4f7e",
            hasBroadcast: true,
            mergeBubbles: true,
            operatorView: {
                canRecoverChat: true,
            },
            integrationId: "5e4dca391affd8000e270256",
            scrubbingRule: 1,
            historyEnabled: true,
            setFlowOnLeave: 12885,
            canRecoverCases: true,
            pageAccessToken:
                "EAANYjNkwzJUBAG1vi6S2qCyAV8R0MC5ZCsF3rlVYZAROrRIUr3zlNVXWFQOnHVOJwp7SvpmIhxCZCsdseCiZC22gZCs6fCjDiCvTSeISwdTs2ODpk9ZBdt2w9fa0KcwJ1BvLyu3igZAVuzJiNb7ncH1YtnGdI8U33AGQEZAIUydW9iQJjbOVLGAe",
            cancelExpressions: "salir",
            redirectWebhookUrl: "",
            cancelExpressionsMessage: "Saliste de la pregunta 👋🏻\n\n¿En qué más te puedo ayudar?",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "10344597217840",
        name: "Instagram",
        type: "Instagram",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {
            trial: true,
            operator: true,
            provider: {
                app: {
                    keyId: "app_5e75370e132b14000f820617",
                    secret: "I9V8miJWbK0A8VhIevI7Czz45RVSIOJOpxpo6liGjTpvy4d196bxyEWVfS14Zf6XbQ4zsvDn3Q-Ced5It6LslQ",
                },
                name: "smooch",
                account: {
                    keyId: "act_5d4889a7db751a001073bd74",
                    secret: "MfWzl40zzx31eiaeJ1ENZIpigD5bEW99IxPXo1RBOpO7ZWJFsZH4MwhoP7XxM_3K9pQeUm1XvNYXLpuS8xCj3A",
                },
                namespace: "e0f2cbcc_1ca9_4a8a_b38a_914e0c9cc679",
                credentials: {
                    appId: "5e4dca27aa83eb000f6c4f7e",
                },
            },
            saveBody: true,
            smoochId: "5e4dca27aa83eb000f6c4f7e",
            isSandbox: true,
            hasBroadcast: true,
            mergeBubbles: true,
            operatorView: {
                canRecoverChat: true,
            },
            integrationId: "5e4dca391affd8000e270256",
            historyEnabled: true,
            canRecoverCases: true,
            sidebar_settings: [
                {
                    id: "e0094ed0-21f1-41da-a098-20c171f11abc",
                    name: "option",
                    type: "text",
                    label: "opción seleccionada",
                },
                {
                    id: "96f641b6-bd2e-4c5e-9ff0-f519c09c54a0",
                    name: "cityName",
                    type: "text",
                    label: "ciudad",
                },
                {
                    id: "f595717b-4ed6-4aa7-9da8-70a2468d3fdf",
                    name: "legalId",
                    type: "text",
                    label: "cédula",
                },
                {
                    id: "8f9286cc-9601-470c-bfeb-9e5dc4a5bb28",
                    name: "fullName",
                    type: "text",
                    label: "nombre",
                },
                {
                    id: "bf6b6a37-3f40-4877-ba91-84888cbc9cb0",
                    name: "phone",
                    type: "text",
                    label: "teléfono",
                },
                {
                    id: "01229a0c-c873-44dc-88e1-7bcc3d3694a5",
                    name: "observations",
                    type: "textbox",
                    label: "observaciones",
                },
            ],
            cancelExpressions: "salir",
            cancelExpressionsMessage: "Saliste de la pregunta 👋🏻\n\n¿En qué más te puedo ayudar?",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "111849250229607_Feed",
        name: "Jelou Aqua",
        type: "Facebook_Feed",
        imageUrl: "https://s3.us-west-2.amazonaws.com/cdn.devlabs.tech/botImage/kyxbiapr-73295359_111850330229499_6514272254707105792_n.jpg",
        companyId: 135,
        inProduction: 1,
        properties: {
            page: {
                name: "Aqua",
                profilePicture:
                    "https://s3.us-west-2.amazonaws.com/cdn.devlabs.tech/botImage/kyxbiapr-73295359_111850330229499_6514272254707105792_n.jpg",
            },
            replies: {
                teams: [399, 164, 165, 166],
            },
            operator: true,
            saveBody: true,
            realBotId: "111849250229607",
            isTheadBotv2: true,
            cancelExpressions: "",
            whatsapp_messages: {
                leaveMenuMessage: "Salida",
            },
            redirectWebhookUrl: "",
            sessionExpiredMessages: {},
            cancelExpressionsMessage: {},
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 1,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "593959246673",
        name: "Jelou Cloud Api",
        type: "Whatsapp",
        imageUrl: "https://s3.us-west-2.amazonaws.com/cdn.devlabs.tech/botImage/ked9ae0e-jelou.jpeg",
        companyId: 135,
        inProduction: 0,
        properties: {
            operator: true,
            provider: {
                name: "whatsapp_cloud",
                phoneNumberID: "103843285669958",
                businessAccountID: "101292195930936",
            },
            saveBody: true,
            sendAudio: true,
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 1,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "972ba658-4de6-4fe1-bc6c-9eab887c8210",
        name: "Jelou Dev Email",
        type: "email",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {
            operator: true,
            provider: {
                name: "postmark",
                email: "soporte@jeloudev.jlu.ai",
                apiUrl: "https://api.postmarkapp.com",
                accessToken: "449c55e8-527a-4d87-8741-e23657208a0c",
            },
            signatures: {
                by: "user",
            },
            supportTickets: {
                teams: [551],
                emails: ["soporte@jeloudev.jlu.ai", "widget@jeloudev.jlu.ai"],
                signatures: {
                    by: "user",
                },
                responseAll: true,
                forceTicketAssign: true,
                checkClientResponse: true,
            },
            eventOnCloseTicket: 41,
            onCloseTicketFlowIdExecutor: 25453,
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 2,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "100589555707631",
        name: "Jelou Dev Facebook",
        type: "Facebook",
        imageUrl: "https://s3.us-west-2.amazonaws.com/cdn.devlabs.tech/botImage/ked9a8i0-jelou.jpeg",
        companyId: 135,
        inProduction: 0,
        properties: {
            audioEnabled: true,
            onLeaveFlowId: 12885,
            scrubbingRule: 1,
            RequestLockEnabled: true,
            redirectWebhookUrl: "",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "17841450250154428",
        name: "Jelou Dev Instagram",
        type: "Instagram",
        imageUrl: "https://s3.us-west-2.amazonaws.com/cdn.devlabs.tech/botImage/ked9a8i0-jelou.jpeg",
        companyId: 135,
        inProduction: 0,
        properties: {},
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "+123-sms",
        name: "Jelou Dev Sms",
        type: "Sms",
        imageUrl: null,
        companyId: 135,
        inProduction: 1,
        properties: {
            provider: {
                name: "massend",
                credentials: {
                    password: "39478jenale",
                    username: "jelou",
                },
            },
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "1404514230326472706",
        name: "Jelou Dev Twitter",
        type: "Twitter",
        imageUrl: "https://s3.us-west-2.amazonaws.com/cdn.devlabs.tech/botImage/ked9a8i0-jelou.jpeg",
        companyId: 135,
        inProduction: 0,
        properties: {
            threadBot: true,
            access_token: "1404514230326472706-xJPMPZ2Ew9uriVfFwzU0jiMZpfVJmC",
            consumer_key: "KlyN55nvi1FoY6KxG8CnRLwQU",
            consumer_secret: "h8lwkuG869LcbPVEKEnqrDKXdQUSkAdY76NkxgQQ4jh1jkKmHT",
            access_token_secret: "iBTvjrRe2qWl7B86MGtFDfmgTfpkFawf94RtUatp4tlSJ",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "1363986947119710209",
        name: "Jelou Dev Twitter Dm",
        type: "Twitter",
        imageUrl: "https://s3.us-west-2.amazonaws.com/cdn.devlabs.tech/botImage/ked9a8i0-jelou.jpeg",
        companyId: 135,
        inProduction: 0,
        properties: {
            botId: "1363986947119710209",
            saveBody: true,
            threadBot: "1363986947119710200",
            access_token: "1363986947119710209-EL7K1aos3ZTLPN4ZAr9jQL3RXHmq2n",
            consumer_key: "S9dTOVRg7IRIK66hM8Am3lAVc",
            scrubbingRule: 1,
            messagesToUser: {
                end: "Chaoo!!",
            },
            setFlowOnLeave: true,
            consumer_secret: "B1zZS4tfKoK85QqwdmF8GhKXumO3VAePkdRAlweQNIK7S7dfbP",
            access_token_key: "1363986947119710209-EL7K1aos3ZTLPN4ZAr9jQL3RXHmq2n",
            redirectWebhookUrl: "",
            access_token_secret: "oTRrqBpfUJRlkIgkCbsi90yKl5z8w2sCwsPCSbU6nj7gV",
            onLeaveFlowIdExecutor: 15787,
            onReturnFlowIdExecutor: 15788,
            onLeaveFlowIdEncuestaBrasilExecutor: 15787,
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 2,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "+123456789000",
        name: "Jelou Dev WhatsApp",
        type: "Whatsapp",
        imageUrl: " ",
        companyId: 135,
        inProduction: 1,
        properties: {
            debug: true,
            fuzzy: {
                minConfidence: 0.3,
            },
            withId: true,
            operator: true,
            provider: {
                name: "gupshup",
                appId: "bb0079b9-8616-481f-8a33-fec039f9698e",
                apikey: "tqcocuf4kcnwxsqqshrlummf1rw5ghzb",
                driver: "gupshup",
                appName: "SandboxJelou",
                originalSource: "593939249558",
            },
            saveBody: true,
            sendAudio: true,
            cacheLimits: {
                input: 1,
                option: 3600,
                stored_params: 900,
            },
            enableCalls: true,
            environment: "development",
            get_started: {
                title: "Empezar",
                flowId: -1,
            },
            postRetries: 3,
            mergeBubbles: false,
            operatorView: {
                byTeam: true,
                states: ["end"],
                canSwitch: true,
                timesLimit: {
                    wait: 30,
                },
                workingDays: ["0", "1", "2", "3", "4", "5", "6"],
                workingHours: {
                    finalHour: "23:45",
                    initialHour: "00:00",
                },
                messagesToUser: {
                    end: "Su conversación Expiro! Gracias",
                    wait: "Ups estamos esperando que nos envies un mensaje o esta sesión Expirara.!",
                    endMessageIfIsFromOperator: "Lo sentimos el Operador esta ocupado, para volver a contactarlo poner Solicitar Ticket!",
                    waitMessageIfIsFromOperator: "Mensaje de Alerta cuando el Operador no ha enviado mensaje!!!!!",
                },
                isEnableScheduler: true,
                limitTimeOperator: 7200,
                isEnableWorkingDays: true,
                workingDaysDetailed: [],
            },
            supporticket: {
                forceTicketAssign: true,
            },
            integrationId: "5f6e14e03355c7000ddddadc",
            scrubbingRule: 1,
            supportticket: {
                forceTicketAssign: true,
            },
            webhookEvents: {
                postRetries: 3,
            },
            setFlowOnLeave: true,
            socketProvider: {
                auth: {
                    secret: "i0verx8q6w29zvmwhqiwb2efpccsjmpsdw3nr2e",
                    username: "idkgwf6ghcmyfvvrxqiwwmi",
                },
                name: "talktolk",
            },
            supportTickets: {
                ignoreAssign: true,
                forceTicketAssign: true,
            },
            enabledSwapping: true,
            hiveCredentials: {
                apiUrl: "https://api.eu.hive.id",
                apiSecret: "sk_live_25993451e8e0ca76cfdd547a1c24ce61",
                threshold: 0.7,
                workspaceId: "space_2HN8dSPTj9xTinWLrdQAbxY74WZ",
            },
            PriorityHsmQueue: true,
            facebook_actions: [],
            hasInternalInbox: true,
            sidebar_settings: [
                {
                    id: "7e7ffec4-e98d-46e0-9b9e-152f46767b69",
                    name: "nombre",
                    type: "text",
                    label: "nombre",
                    rules: {
                        rules: "",
                        isObligatory: false,
                    },
                },
                {
                    id: "30ad4a8e-2876-4ecd-88c4-83bbc55609f4",
                    name: "cedula",
                    type: "text",
                    label: "cedula",
                    rules: {
                        rules: "numeric|required",
                        isObligatory: true,
                    },
                },
                {
                    id: "b9a1aaca-8ce9-49bb-8785-ae52c5c4b6b6",
                    name: "ciudad",
                    type: "text",
                    label: "Ciudad",
                    rules: {
                        rules: "",
                        isObligatory: false,
                    },
                },
                {
                    id: "fd45597b-db83-4d36-a91d-ba5eb3773352",
                    name: "telefono",
                    type: "text",
                    label: "Telefono",
                    rules: {
                        rules: "numeric|min:9",
                        isObligatory: false,
                    },
                },
            ],
            cancelExpressions: "salir, exit",
            whatsapp_messages: {
                exitNumber: "0️⃣",
                menuMessage: "*Envía el número de la opción que deseas:*",
                overrideExitMessage: "0️⃣ Para salir del menú de opciones.",
                noValidOptionMessage: 'Este es un mensaje de prueba para: "Mensaje de opcion invalida"',
            },
            notificationWebhook: {
                read: "https://webhook.site/4327fca4-7109-4839-afcb-b01821f1feb3",
                reply: "https://webhook.site/4327fca4-7109-4839-afcb-b01821f1feb3",
                failed: "https://webhook.site/4327fca4-7109-4839-afcb-b01821f1feb3",
                delivered_user: "https://webhook.site/4327fca4-7109-4839-afcb-b01821f1feb3",
            },
            sessionLimitByMonth: 1000,
            customOptionsNumbers: {
                1: "1️⃣",
                2: "2️⃣",
                3: "3️⃣",
                4: "4️⃣",
                5: "5️⃣",
                6: "6️⃣",
                7: "7️⃣",
                8: "8️⃣",
                9: "9️⃣",
                10: "1️⃣0️⃣",
                11: "1️⃣1️⃣",
                12: "1️⃣2️⃣",
                13: "1️⃣3️⃣",
                14: "1️⃣4️⃣",
                15: "1️⃣5️⃣",
            },
            dynamicEventsEnabled: true,
            sessionAlertMessages: {
                input: "{nombre} no he podido ingresar tu solicitud. Por favor ayúdame con la información solicitada.",
                option: "{nombre} no he podido ingresar tu solicitud. Por favor ayúdame con la información solicitada.",
            },
            onLeaveFlowIdExecutor: 15296,
            UserRequestLockEnabled: true,
            notificationWebhookUrl: "https://webhook.site/4327fca4-7109-4839-afcb-b01821f1feb3",
            onReturnFlowIdExecutor: 15337,
            sessionExpiredMessages: {
                input: "Se acabo el tiempo de respuesta de la pregunta.Intentalo mas tarde nuevamente",
                option: "Se acabo el tiempo de respuesta para el menú. Intentalo nuevamente",
            },
            cancelExpressionsMessage: "Saliste de la pregunta ??nn¿En qué más te puedo ayudar?",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 3,
        activeConversations: 1,
        growth: 0,
    },
    {
        id: "062a698a-da08-4397-bc9c-0c038f43da43",
        name: "Jelou Dev Widget",
        type: "Widget",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {},
        state: 1,
        language: "es",
        actualMonthClients: 46,
        lastMonthClients: 434,
        activeConversations: 0,
        growth: 11,
    },
    {
        id: "29bc03e2-688f-4bca-aeda-389942037e4a",
        name: "Jelou Dev Widget",
        type: "Widget",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {},
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "2b67c48c-9b21-42d5-bc22-b40321b00fd8",
        name: "Jelou Dev Widget",
        type: "Widget",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {},
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "2dbf9b25-2590-4a25-9c0b-2bc7aa0d1b3f",
        name: "Jelou Dev Widget",
        type: "Widget",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {},
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "33866fb4-d356-4409-bb57-fbaf85326fef",
        name: "Jelou Dev Widget",
        type: "Widget",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {},
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "43dbcae1-7477-4a79-90cc-ea306f0f8ce7",
        name: "Jelou Dev Widget",
        type: "Widget",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {},
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "54a82cef-f845-4b81-a4f6-0e08607bd496",
        name: "Jelou Dev Widget",
        type: "Widget",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {},
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "a1fe1ae4-cedd-4277-ad18-456a37a7e767",
        name: "Jelou Dev Widget",
        type: "Widget",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {},
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "a6c95322-f419-42b8-a762-5c8eaf20a874",
        name: "Jelou Dev Widget",
        type: "Widget",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {},
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "d0b2f9bf-f032-4d54-a2fb-f9c20951c123",
        name: "Jelou Dev Widget",
        type: "Widget",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {},
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "497a8735-9848-4482-8102-2bf766d2400a",
        name: "Jelou Dev Zendesk",
        type: "Whatsapp",
        imageUrl: " ",
        companyId: 135,
        inProduction: 1,
        properties: {
            provider: {
                name: "gupshup",
                appId: "e57205fe-4b25-4ec8-b33b-e00166da7ece",
                apikey: "tqcocuf4kcnwxsqqshrlummf1rw5ghzb",
                driver: "gupshup",
                appName: "JelouDemosWhatsApp",
                originalSource: "593985263429",
            },
            cacheLimits: {
                input: 3600,
                option: 60,
            },
            mergeBubbles: "",
            socketProvider: {
                name: "zendesk",
                email: "omar@jelou.ai/token",
                apiUrl: "https://d3v-jelousupport.zendesk.com",
                password: "fEev4sEIQL4FdY2suO8UrXHuRdYhAc1jIJsDDurf",
            },
            sidebar_settings: [
                {
                    id: "569e129a-9f3f-4631-a49b-b6dbe3dd301b",
                    name: "cedula",
                    type: "text",
                    label: "cedula",
                    rules: {
                        rules: "numeric",
                        isObligatory: false,
                    },
                },
            ],
            cancelExpressions: "salir, kiwi, exit",
            whatsapp_messages: {
                menuMessage: "Envía el número de la opción que deseas:",
                leaveMenuMessage: "Saliste del modo de selección. ¿En qué más te puedo ayudar?",
                noValidOptionMessage:
                    "Esa opción no es válida. Debes escribir el número de las opciones indicadas anteriormente o envía 0 para continuar.",
                menuMessageInteractive: "Selecciona la opción que deseas:",
            },
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "109586661529248",
        name: "Jelou Inori",
        type: "Facebook",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {
            trial: true,
            operator: true,
            provider: {
                app: {
                    keyId: "app_5e75370e132b14000f820617",
                    secret: "I9V8miJWbK0A8VhIevI7Czz45RVSIOJOpxpo6liGjTpvy4d196bxyEWVfS14Zf6XbQ4zsvDn3Q-Ced5It6LslQ",
                },
                name: "smooch",
                account: {
                    keyId: "act_5d4889a7db751a001073bd74",
                    secret: "MfWzl40zzx31eiaeJ1ENZIpigD5bEW99IxPXo1RBOpO7ZWJFsZH4MwhoP7XxM_3K9pQeUm1XvNYXLpuS8xCj3A",
                },
                namespace: "e0f2cbcc_1ca9_4a8a_b38a_914e0c9cc679",
                credentials: {
                    appId: "5e4dca27aa83eb000f6c4f7e",
                },
            },
            smoochId: "5e4dca27aa83eb000f6c4f7e",
            isSandbox: true,
            hasBroadcast: true,
            mergeBubbles: true,
            operatorView: {
                canRecoverChat: true,
            },
            integrationId: "5e4dca391affd8000e270256",
            historyEnabled: true,
            canRecoverCases: true,
            sidebar_settings: [
                {
                    id: "e0094ed0-21f1-41da-a098-20c171f11abc",
                    name: "option",
                    type: "text",
                    label: "opción seleccionada",
                },
                {
                    id: "96f641b6-bd2e-4c5e-9ff0-f519c09c54a0",
                    name: "cityName",
                    type: "text",
                    label: "ciudad",
                },
                {
                    id: "f595717b-4ed6-4aa7-9da8-70a2468d3fdf",
                    name: "legalId",
                    type: "text",
                    label: "cédula",
                },
                {
                    id: "8f9286cc-9601-470c-bfeb-9e5dc4a5bb28",
                    name: "fullName",
                    type: "text",
                    label: "nombre",
                },
                {
                    id: "bf6b6a37-3f40-4877-ba91-84888cbc9cb0",
                    name: "phone",
                    type: "text",
                    label: "teléfono",
                },
                {
                    id: "01229a0c-c873-44dc-88e1-7bcc3d3694a5",
                    name: "observations",
                    type: "textbox",
                    label: "observaciones",
                },
            ],
            cancelExpressions: "salir",
            redirectWebhookUrl: "https://eq445tdbjt.sharedwithexpose.com",
            cancelExpressionsMessage: "Saliste de la pregunta 👋🏻\n\n¿En qué más te puedo ayudar?",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "1fea4c08-265a-468e-9469-baa4181696c7",
        name: "Jelou Test",
        type: "Whatsapp",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {
            trial: true,
            operator: true,
            provider: {
                name: "gupshup",
                appId: "e57205fe-4b25-4ec8-b33b-e00166da7ece",
                apikey: "tqcocuf4kcnwxsqqshrlummf1rw5ghzb",
                driver: "gupshup",
                appName: "JelouDemosWhatsApp",
                originalSource: "593985263429",
            },
            isSandbox: true,
            hasBroadcast: true,
            mergeBubbles: true,
            operatorView: {
                canRecoverChat: true,
            },
            historyEnabled: true,
            canRecoverCases: true,
            sidebar_settings: [
                {
                    id: "e0094ed0-21f1-41da-a098-20c171f11abc",
                    name: "option",
                    type: "text",
                    label: "opción seleccionada",
                },
                {
                    id: "96f641b6-bd2e-4c5e-9ff0-f519c09c54a0",
                    name: "cityName",
                    type: "text",
                    label: "ciudad",
                },
                {
                    id: "f595717b-4ed6-4aa7-9da8-70a2468d3fdf",
                    name: "legalId",
                    type: "text",
                    label: "cédula",
                },
                {
                    id: "8f9286cc-9601-470c-bfeb-9e5dc4a5bb28",
                    name: "fullName",
                    type: "text",
                    label: "nombre",
                },
                {
                    id: "bf6b6a37-3f40-4877-ba91-84888cbc9cb0",
                    name: "phone",
                    type: "text",
                    label: "teléfono",
                },
                {
                    id: "01229a0c-c873-44dc-88e1-7bcc3d3694a5",
                    name: "observations",
                    type: "textbox",
                    label: "observaciones",
                },
            ],
            cancelExpressions: "salir",
            cancelExpressionsMessage: "Saliste de la pregunta 👋🏻\n\n¿En qué más te puedo ayudar?",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "98918d34-64d6-4d0e-a509-0d53c15befba",
        name: "Jelou Workflows",
        type: "Whatsapp",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {
            token: "WXYOJPIHLOEEHACHHLRJBYYLUVJCI73X",
            operator: true,
            provider: {
                name: "gupshup",
                appId: "e57205fe-4b25-4ec8-b33b-e00166da7ece",
                apikey: "tqcocuf4kcnwxsqqshrlummf1rw5ghzb",
                driver: "gupshup",
                appName: "JelouDemosWhatsApp",
                originalSource: "593985263429",
            },
            witAppId: "c1a16747-0f5e-4b53-a4a5-f466bcd4a13d",
            nlpDriver: "wit",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "10149999832154161",
        name: "Karen Lauez",
        type: "Facebook",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {
            trial: true,
            operator: true,
            provider: {
                app: {
                    keyId: "app_5e75370e132b14000f820617",
                    secret: "I9V8miJWbK0A8VhIevI7Czz45RVSIOJOpxpo6liGjTpvy4d196bxyEWVfS14Zf6XbQ4zsvDn3Q-Ced5It6LslQ",
                },
                name: "smooch",
                account: {
                    keyId: "act_5d4889a7db751a001073bd74",
                    secret: "MfWzl40zzx31eiaeJ1ENZIpigD5bEW99IxPXo1RBOpO7ZWJFsZH4MwhoP7XxM_3K9pQeUm1XvNYXLpuS8xCj3A",
                },
                namespace: "e0f2cbcc_1ca9_4a8a_b38a_914e0c9cc679",
                credentials: {
                    appId: "5e4dca27aa83eb000f6c4f7e",
                },
            },
            smoochId: "5e4dca27aa83eb000f6c4f7e",
            isSandbox: true,
            hasBroadcast: true,
            mergeBubbles: true,
            operatorView: {
                canRecoverChat: true,
            },
            integrationId: "5e4dca391affd8000e270256",
            historyEnabled: true,
            canRecoverCases: true,
            sidebar_settings: [
                {
                    id: "e0094ed0-21f1-41da-a098-20c171f11abc",
                    name: "option",
                    type: "text",
                    label: "opción seleccionada",
                },
                {
                    id: "96f641b6-bd2e-4c5e-9ff0-f519c09c54a0",
                    name: "cityName",
                    type: "text",
                    label: "ciudad",
                },
                {
                    id: "f595717b-4ed6-4aa7-9da8-70a2468d3fdf",
                    name: "legalId",
                    type: "text",
                    label: "cédula",
                },
                {
                    id: "8f9286cc-9601-470c-bfeb-9e5dc4a5bb28",
                    name: "fullName",
                    type: "text",
                    label: "nombre",
                },
                {
                    id: "bf6b6a37-3f40-4877-ba91-84888cbc9cb0",
                    name: "phone",
                    type: "text",
                    label: "teléfono",
                },
                {
                    id: "01229a0c-c873-44dc-88e1-7bcc3d3694a5",
                    name: "observations",
                    type: "textbox",
                    label: "observaciones",
                },
            ],
            cancelExpressions: "salir",
            cancelExpressionsMessage: "Saliste de la pregunta 👋🏻\n\n¿En qué más te puedo ayudar?",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "+593963219808001-Koukin",
        name: "Koukin Bot",
        type: "Whatsapp",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTLCw_mjZoHJb9pwZz0MJLBWdKnkj0yEJjtR7C42kJse7hw5q0_&usqp=CAU",
        companyId: 135,
        inProduction: 0,
        properties: {
            _id: "5f15f97900906869b69ea9f3",
            botId: "+593963219808001-Koukin",
            billing: {
                type: "default",
            },
            operator: true,
            provider: {
                app: {
                    keyId: "app_5f6d0879c80fa7000ca7ce7a",
                    secret: "h4LPgIlOYb7eVuwz17DrwLtsowNAfvXQHgnv7-XqAE4qvBCUhvKCoIRkB1hdQ0uST5iQGAkRZwqNGqoYcGmFQg",
                },
                name: "gupshup",
                appId: "bb0079b9-8616-481f-8a33-fec039f9698e",
                apikey: "tqcocuf4kcnwxsqqshrlummf1rw5ghzb",
                driver: "gupshup",
                account: {
                    keyId: "act_5d4889a7db751a001073bd74",
                    secret: "MfWzl40zzx31eiaeJ1ENZIpigD5bEW99IxPXo1RBOpO7ZWJFsZH4MwhoP7XxM_3K9pQeUm1XvNYXLpuS8xCj3A",
                },
                appName: "SandboxJelou",
                namespace: "e0f2cbcc_1ca9_4a8a_b38a_914e0c9cc679",
                credentials: {
                    appId: "5f6d07e35a9b2b000db85e02",
                },
                originalSource: "593939249558",
            },
            smoochId: "5f6d07e35a9b2b000db85e02",
            createdAt: "2020-07-20T20:07:22.053Z",
            updatedAt: "2020-07-20T20:07:22.053Z",
            get_started: {
                title: "Empezar",
                flowId: -1,
            },
            operatorView: {
                states: ["wait", "end"],
                saveFile: {
                    type: "pdf",
                    template: "gea-chats",
                },
                timesLimit: {
                    wait: 60,
                },
                workingDays: ["1", "2", "3", "4", "5", "6", "7"],
                usersSession: ["user"],
                workingHours: {
                    finalHour: "18:00",
                    initialHour: "9:00",
                },
                messagesToUser: {
                    end: "Al parecer no te encuentras disponible por el momento ☹. Para volver a chatear envía la palabra _*menú*_ y escoge una de las opciones disponibles.Recuerda que estoy para ayudarte cuando lo necesites 🙃.",
                    wait: "Esta sesión pronto se cerrara, escribe un mensaje si deseas continuar con la conversación.",
                    operatorCloseSession: "Fue un gusto atenderte, si deseas comunicarte nuevamente escribe *ayuda*.",
                    endMessageIfIsFromOperator:
                        "Al momento me encuentro revisando tu requerimiento. En el transcurso del día me comunicaré por esta vía para brindarte más información. No dudes en contactarnos nuevamente enviando la palabra _*hola*_ y luego selecciona una de las opciones disponibles del menú.",
                    waitMessageIfIsFromOperator: "Este es el mensaje final cuando el ultimo mensaje es de operador",
                },
                limitTimeOperator: 60,
            },
            integrationId: "5d4887b54afbd6000fc29dee",
            developerToken: "fe59f203e916af3c3278f7f9d3d0ab16",
            historyEnabled: true,
            operatorLimits: 1,
            socketProvider: {
                auth: {
                    secret: "i0verx8q6w29zvmwhqiwb2efpccsjmpsdw3nr2e",
                    username: "idkgwf6ghcmyfvvrxqiwwmi",
                },
                name: "talktolk",
            },
            facebook_actions: [],
            cancelExpressions: "salir,cancelar,leave",
            redirectWebhookUrl: "https://bhea16ir1g.sharedwithexpose.com",
            sessionAlertMessages: {
                input: "Recuerda que estamos esperando tu respuesta a la pregunta.",
                option: "Recuerda que estamos esperando que ingreses un opcion del menu.",
            },
            sessionExpiredMessages: {
                input: "Se acabo el tiempo de respuesta de la pregunta. Intentalo mas tarde nuevamente",
                option: "Se acabo el tiempo de respuesta para el menu. Intentalo nuevamente",
            },
            cancelExpressionsMessage: "Acabas de salir de la pregunta",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "711360122219500",
        name: "Koukin Bot FB",
        type: "Facebook",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTLCw_mjZoHJb9pwZz0MJLBWdKnkj0yEJjtR7C42kJse7hw5q0_&usqp=CAU",
        companyId: 135,
        inProduction: 0,
        properties: {
            webhookUrl: "http://www.mocky.io/v2/5e3d98172d0000a57dd95e61",
            get_started: {
                title: "Empezar",
                flowId: "7764",
            },
            postRetries: 3,
            webhookEvents: {
                postRetries: 3,
                "message:delivery:user": "http://www.mocky.io/v2/5e3d98172d0000a57dd95e61",
            },
            historyEnabled: true,
            facebook_actions: [
                {
                    title: "Ayuda",
                    flowId: "7765",
                },
            ],
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "18400056",
        name: "Koukin Twitter",
        type: "Twitter",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTLCw_mjZoHJb9pwZz0MJLBWdKnkj0yEJjtR7C42kJse7hw5q0_&usqp=CAU",
        companyId: 135,
        inProduction: 0,
        properties: {
            access_token: null,
            consumer_key: null,
            consumer_secret: null,
            access_token_secret: null,
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "c1104991-d964-47ed-8c2c-781aa528183a",
        name: "Netlife test email",
        type: "email",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {
            operator: true,
            provider: {
                name: "postmark",
                email: "soporte@netlife.jlu.ai",
                apiUrl: "https://api.postmarkapp.com",
                accessToken: "9ced78aa-be28-4220-a5c1-439b10beaa7e",
            },
            signatures: {
                by: "team",
            },
            supportTickets: {
                teams: [382, 383],
                emails: ["soporte@netlife.jlu.ai", "atencionalcliente@netlife.jlu.ai"],
                signatures: {
                    by: "user",
                },
            },
            eventOnCloseTicket: 19,
            ticketExpirationTime: 259200,
            onCloseTicketFlowIdExecutor: 18868,
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "593968493126",
        name: "Numero Baneado",
        type: "Whatsapp",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTLCw_mjZoHJb9pwZz0MJLBWdKnkj0yEJjtR7C42kJse7hw5q0_&usqp=CAU",
        companyId: 135,
        inProduction: 0,
        properties: 5,
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "be925c2f-df42-46f1-9335-b06cd92f3326",
        name: "prueba",
        type: "Widget",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {},
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "109830044656380",
        name: "prueba fb",
        type: "Facebook",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {
            trial: true,
            operator: true,
            provider: {
                app: {
                    keyId: "app_5e75370e132b14000f820617",
                    secret: "I9V8miJWbK0A8VhIevI7Czz45RVSIOJOpxpo6liGjTpvy4d196bxyEWVfS14Zf6XbQ4zsvDn3Q-Ced5It6LslQ",
                },
                name: "smooch",
                account: {
                    keyId: "act_5d4889a7db751a001073bd74",
                    secret: "MfWzl40zzx31eiaeJ1ENZIpigD5bEW99IxPXo1RBOpO7ZWJFsZH4MwhoP7XxM_3K9pQeUm1XvNYXLpuS8xCj3A",
                },
                namespace: "e0f2cbcc_1ca9_4a8a_b38a_914e0c9cc679",
                credentials: {
                    appId: "5e4dca27aa83eb000f6c4f7e",
                },
            },
            smoochId: "5e4dca27aa83eb000f6c4f7e",
            isSandbox: true,
            hasBroadcast: true,
            mergeBubbles: true,
            operatorView: {
                canRecoverChat: true,
            },
            integrationId: "5e4dca391affd8000e270256",
            historyEnabled: true,
            canRecoverCases: true,
            sidebar_settings: [
                {
                    id: "e0094ed0-21f1-41da-a098-20c171f11abc",
                    name: "option",
                    type: "text",
                    label: "opción seleccionada",
                },
                {
                    id: "96f641b6-bd2e-4c5e-9ff0-f519c09c54a0",
                    name: "cityName",
                    type: "text",
                    label: "ciudad",
                },
                {
                    id: "f595717b-4ed6-4aa7-9da8-70a2468d3fdf",
                    name: "legalId",
                    type: "text",
                    label: "cédula",
                },
                {
                    id: "8f9286cc-9601-470c-bfeb-9e5dc4a5bb28",
                    name: "fullName",
                    type: "text",
                    label: "nombre",
                },
                {
                    id: "bf6b6a37-3f40-4877-ba91-84888cbc9cb0",
                    name: "phone",
                    type: "text",
                    label: "teléfono",
                },
                {
                    id: "01229a0c-c873-44dc-88e1-7bcc3d3694a5",
                    name: "observations",
                    type: "textbox",
                    label: "observaciones",
                },
            ],
            cancelExpressions: "salir",
            cancelExpressionsMessage: "Saliste de la pregunta 👋🏻\n\n¿En qué más te puedo ayudar?",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "101456965714281",
        name: "Prueba Instagram",
        type: "Instagram",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {
            trial: true,
            operator: true,
            provider: {
                app: {
                    keyId: "app_5e75370e132b14000f820617",
                    secret: "I9V8miJWbK0A8VhIevI7Czz45RVSIOJOpxpo6liGjTpvy4d196bxyEWVfS14Zf6XbQ4zsvDn3Q-Ced5It6LslQ",
                },
                name: "smooch",
                account: {
                    keyId: "act_5d4889a7db751a001073bd74",
                    secret: "MfWzl40zzx31eiaeJ1ENZIpigD5bEW99IxPXo1RBOpO7ZWJFsZH4MwhoP7XxM_3K9pQeUm1XvNYXLpuS8xCj3A",
                },
                namespace: "e0f2cbcc_1ca9_4a8a_b38a_914e0c9cc679",
                credentials: {
                    appId: "5e4dca27aa83eb000f6c4f7e",
                },
            },
            saveBody: true,
            smoochId: "5e4dca27aa83eb000f6c4f7e",
            isSandbox: true,
            hasBroadcast: true,
            mergeBubbles: true,
            operatorView: {
                canRecoverChat: true,
            },
            integrationId: "5e4dca391affd8000e270256",
            historyEnabled: true,
            canRecoverCases: true,
            sidebar_settings: [
                {
                    id: "e0094ed0-21f1-41da-a098-20c171f11abc",
                    name: "option",
                    type: "text",
                    label: "opción seleccionada",
                },
                {
                    id: "96f641b6-bd2e-4c5e-9ff0-f519c09c54a0",
                    name: "cityName",
                    type: "text",
                    label: "ciudad",
                },
                {
                    id: "f595717b-4ed6-4aa7-9da8-70a2468d3fdf",
                    name: "legalId",
                    type: "text",
                    label: "cédula",
                },
                {
                    id: "8f9286cc-9601-470c-bfeb-9e5dc4a5bb28",
                    name: "fullName",
                    type: "text",
                    label: "nombre",
                },
                {
                    id: "bf6b6a37-3f40-4877-ba91-84888cbc9cb0",
                    name: "phone",
                    type: "text",
                    label: "teléfono",
                },
                {
                    id: "01229a0c-c873-44dc-88e1-7bcc3d3694a5",
                    name: "observations",
                    type: "textbox",
                    label: "observaciones",
                },
            ],
            cancelExpressions: "salir",
            cancelExpressionsMessage: "Saliste de la pregunta 👋🏻\n\n¿En qué más te puedo ayudar?",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "+593969488119",
        name: "PRUEBAS SETTINGS",
        type: "Whatsapp",
        imageUrl: "",
        companyId: 135,
        inProduction: 0,
        properties: {
            hasBroadcast: true,
            operatorView: {
                byTeam: true,
                states: ["end", "wait"],
                canSwitch: true,
                uniqueSession: true,
                canRecoverChat: true,
                messagesToUser: {
                    end: "expiro",
                    wait: "en espera",
                    operatorCloseSession: "cerrando",
                },
                canRecoverCases: true,
                assignationBalancer: {
                    balancer: "currentLoad",
                },
                notificationsToOperator: {
                    wait: "va a cerrar",
                },
            },
            cancelExpressions: "chao,`bye",
            whatsapp_messages: {
                exitMessage: "",
                menuMessage: "instru",
                leaveMenuMessage: "salir menu",
                noValidOptionMessage: "invalid",
            },
            hasSentimentAnalysis: true,
            sessionExpiredMessages: {
                input: "",
                option: "test op expir",
            },
            cancelExpressionsMessage: "",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "+593922198282",
        name: "s",
        type: "Facebook",
        imageUrl: "",
        companyId: 135,
        inProduction: 0,
        properties: null,
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "109080641722769",
        name: "Sandbox Jelou",
        type: "Facebook",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {
            migrate: true,
            operator: true,
            cancelExpressions: "salir",
            redirectWebhookUrl: "",
            cancelExpressionsMessage: "Saliste de la pregunta 👋🏻\n\n¿En qué más te puedo ayudar?",
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "+593921209933",
        name: "Source Botsn",
        type: "Facebook",
        imageUrl: "",
        companyId: 135,
        inProduction: 0,
        properties: null,
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "d8184a13-461a-4e59-8327-ab2fcb8372b9",
        name: "Test Widget Empty",
        type: "Widget",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {
            webhookUrls: {
                "user-new": ["http://localhost:7771"],
                undefined: [],
                "room-message": ["http://localhost:7777", "http://localhost:7771"],
            },
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "d60eab2d-403c-41e2-9dd8-62df7813599c",
        name: "test-webhooks-widget",
        type: "Widget",
        imageUrl: null,
        companyId: 135,
        inProduction: 0,
        properties: {
            webhookUrls: {
                "room-message": [],
            },
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 0,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "1363986947119710200",
        name: "Twitter Replies",
        type: "Twitter_replies",
        imageUrl: "https://s3.us-west-2.amazonaws.com/cdn.devlabs.tech/botImage/kz7kayzg-yutcotsb_400x400.jpg",
        companyId: 135,
        inProduction: 1,
        properties: {
            page: {
                name: "Publicaciones",
                profilePicture: "https://s3.us-west-2.amazonaws.com/cdn.devlabs.tech/botImage/kz7kayzg-yutcotsb_400x400.jpg",
            },
            botId: "1363986947119710200",
            operator: true,
            saveBody: true,
            realBotId: "1363986947119710209",
            threadBot: true,
            access_token: "1363986947119710209-EL7K1aos3ZTLPN4ZAr9jQL3RXHmq2n",
            consumer_key: "S9dTOVRg7IRIK66hM8Am3lAVc",
            isTheadBotv2: true,
            operatorView: {
                tickets: {
                    expirationTime: 6000,
                },
            },
            scrubbingRule: 1,
            setFlowOnLeave: true,
            consumer_secret: "B1zZS4tfKoK85QqwdmF8GhKXumO3VAePkdRAlweQNIK7S7dfbP",
            queuePriorities: {
                reply: 2,
                default: 99,
            },
            access_token_key: "1363986947119710209-EL7K1aos3ZTLPN4ZAr9jQL3RXHmq2n",
            redirectWebhookUrl: "https://050e-2800-bf0-80f0-13bb-5d97-ee98-5c48-36bf.sa.ngrok.io",
            access_token_secret: "oTRrqBpfUJRlkIgkCbsi90yKl5z8w2sCwsPCSbU6nj7gV",
            onLeaveFlowIdExecutor: 15787,
            onReturnFlowIdExecutor: 15788,
        },
        state: 1,
        language: "es",
        actualMonthClients: 0,
        lastMonthClients: 37,
        activeConversations: 0,
        growth: 0,
    },
    {
        id: "widget-test-jelou",
        name: "Widget Test Jelou",
        type: "Widget",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTLCw_mjZoHJb9pwZz0MJLBWdKnkj0yEJjtR7C42kJse7hw5q0_&usqp=CAU",
        companyId: 135,
        inProduction: 0,
        properties: {
            operator: true,
            operatorView: {
                byTeam: true,
                groups: {
                    waitTime: 10,
                    expirationTime: 25,
                    alertMessageExpiration: "Atenção! em breve está conversa será encerrada por inatividade, caso tenha alguma dúvida nos avise",
                    closeMessageExpiration: "Chat encerrado por inatividade, caso precise de ajuda contate nosso suporte",
                    alertMessageExpirationOperator:
                        "Alert: Mensaje de expiración debido al ultimo mensaje del operador, esperando respuesta del usuario",
                },
                states: ["end", "wait"],
                timesLimit: {
                    wait: 60,
                },
                messagesToUser: {
                    end: "Esta sesión ha expirado.",
                    wait: "Esta sesión terminará pronto.",
                },
                limitTimeOperator: 120,
            },
        },
        state: 1,
        language: "es",
        actualMonthClients: 1,
        lastMonthClients: 3,
        activeConversations: 0,
        growth: 34,
    },
];
