module.exports = {
    arrowParens: "always",
    bracketSpacing: true,
    endOfLine: "auto",
    htmlWhitespaceSensitivity: "css",
    jsxBracketSameLine: true,
    jsxSingleQuote: false,
    printWidth: 150,
    proseWrap: "preserve",
    semi: true,
    singleQuote: false,
    tabWidth: 4,
    trailingComma: "es5",
    useTabs: false,
};
